# Generated by Django 3.1.6 on 2021-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='Имя'),
        ),
    ]
