# Generated by Django 3.1.6 on 2021-02-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_status',
            new_name='status',
        ),
    ]
