# Generated by Django 3.1.6 on 2021-02-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210222_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.task'),
        ),
    ]
