# Generated by Django 3.1.6 on 2021-02-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210213_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['name']},
        ),
    ]
