# Generated by Django 3.1.6 on 2021-02-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210220_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(to='tasks.Label', verbose_name='Метки'),
        ),
    ]
