# Generated by Django 3.1.6 on 2021-02-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210220_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, to='tasks.Label', verbose_name='Метки'),
        ),
    ]
